name: Orchestration Levels - Piwik ETL

on:
  #schedule: - cron: '0 2 * * *'  # Daily at 2 AM UTC
  workflow_dispatch:

jobs:
  etl:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Create .env file
      run: |
        cat << EOF > .env
        AUTH_URL=${{ secrets.AUTH_URL }}
        BASE_URL=${{ secrets.BASE_URL }}
        CLIENT_ID=${{ secrets.CLIENT_ID }}
        CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}
        WEBSITE_ID=${{ secrets.WEBSITE_ID }}
        S3_BUCKET=${{ secrets.S3_BUCKET }}
        AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION=${{ secrets.AWS_REGION }}
        EOF
    
    - name: Build Docker image
      run: |
        docker build -t piwik-etl .
    
    - name: Run ETL with Docker
      run: |
        docker run --rm --env-file .env piwik-etl